server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8080/eureka/

logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
              
zuul:
  routes:
    buildings:
      path: /building/**
      serviceId: building-service
    employee:
      path: /employee/**
      serviceId: employee-service
    reservation:
      path: /reservation/**
      serviceId: reservation-service